# connection postgres_sql
# run the docker :- docker compose up -d(detach)
services:
  db:
    container_name: postgres
    image: postgres:16.3
    environment:
      POSTGRES_USER: nikul
      POSTGRES_PASSWORD: nikul123
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

  fullstack-app:
    container_name: fullstack-app
    image: technuzone/fullstack-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/customer
    ports:
      - "8080:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped

  customer-web:
    container_name: customer-web
    image: technuzone/customer-web
    build:
      context: customer-web
    ports:
      - "3000:5173"
    depends_on:
      - fullstack-app
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: