name: CI- Build Backend

on:
    pull_request:
        branches:
            - main
    paths:
        - backend/**

jobs:
    build:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:16.3
                env:
                    POSTGRES_USER: nikul
                    POSTGRES_PASSWORD: nikul123
                    POSTGRES_DB: customer
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5



        defaults:
            run:
                working-directory: ./backend

        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'temurin'
                  cache: 'maven'

            - name: Build and run Unit/Integration Tests with maven
              run: mvn -ntp -B verify